# load joint trajectory controller
controller_list:
  - name: kuka_arm/arm_manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  - name: kuka_arm/gripper_manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_gripper_finger_joint
      - right_gripper_finger_joint
