controller_list:
  - name: fake_arm_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_gripper_finger_joint
      - right_gripper_finger_joint
initial:  # Define initial robot poses per group
  - group: arm_manipulator
    pose: ZERO
  - group: gripper
    pose: CLOSED